language: shell
git:
  depth: false
os:
  - osx
  - windows
  - linux
dist: xenial
stages:
  - test
env:
 matrix:
    - JDK="adopt@1.11.0"
    - JDK="adopt-openj9@1.11.0"
    - JDK="adopt@1.12.0"
    - JDK="adopt-openj9@1.12.0"
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/