/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conrec;

import org.junit.Test;
import utils.Demo;

import static org.junit.Assert.*;

public class RunDemo {
    public void run() {
        new Demo();
    }
}
