name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, windows-2025, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.24
      - name: Determine dry-run flag
        id: check_branch
        shell: bash
        run: |
          ruby << 'RUBY' >> $GITHUB_OUTPUT
            branch = ENV['GITHUB_REF'].sub(/^refs\/heads\//, '')
            keywords = %w[gradle kotlin publish release deploy]
            dry = keywords.any? { |kw| branch.include?(kw) } ? '' : '--dry-run'
            puts "dry_run=#{dry}"
          RUBY
      - uses: DanySK/build-check-deploy-gradle-action@4.0.7
        with:
          deploy-command: >-
            ./gradlew
            publishAllPublicationsToProjectLocalRepository 
            zipMavenCentralPortalPublication 
            releaseMavenCentralPortalPublication
            ${{ steps.check_branch.outputs.dry_run }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          should-run-codecov: ${{ runner.os == 'Linux' }}
          should-deploy: >-
            ${{
              runner.os == 'Linux'
              && !github.event.repository.fork
              && (
                github.event_name != 'pull_request'
                || github.event.pull_request.head.repo.full_name == github.repository
              )
            }}
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
  release:
    concurrency:
      # Only one release job at a time. Strictly sequential.
      group: release-${{ github.event.number || github.ref }}
    needs:
      - build
    runs-on: ubuntu-24.04
    if: >-
      !github.event.repository.fork
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name == github.repository
      )
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Install Node
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: package.json
      - uses: DanySK/build-check-deploy-gradle-action@4.0.7
        with:
          retries-on-failure: '1'
          build-command: true
          check-command: true
          deploy-command: |
            npm install
            npx semantic-release
          should-run-codecov: false
          should-deploy: true
          github-token: ${{ github.token }}
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
  success:
    runs-on: ubuntu-24.04
    needs:
      - release
      - build
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
